defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 20
  username: ENTER_USERNAME
  password: ENTER_PASSWORD
  min_messages: WARNING

development:
  <<: *defaults
  database: fergie_development

test:
  <<: *defaults
  database: fergie_test

production:
  <<: *defaults
  database: fergie_development
